# Change these first
owner: must-icts # Your GitHub organization or username, where this repository lives
repo: uptimes # The name of this repository

sites:
  - name: MUST
    url: https://www.must.ac.ug
  - name: VLE
    url: https://vle.must.ac.ug
  - name: Library
    url: https://elib.must.ac.ug
  - name: IR
    url: https://ir.must.ac.ug
  - name: Journals
    url: https://journals.must.ac.ug
  - name: Uni Portal
    url: https://systems.must.ac.ug
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptimes
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: MUST Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
